"""Where classical features and embeddings disagree, per zone × classifier.

Crosses the four exported classified maps pairwise (clasicas-{clf} vs
embeddings-{clf}, for clf in {rf, knn}), tiles only the disagreement pixels
and writes the summary percentages to data/desacuerdo.json.

  uv run python scripts/05_desacuerdo.py --exports-dir /path/to/exports --corrida 2026-08-09a

Tiles land in tiles/{corrida}/{zona}/{campania}/desacuerdo-{rf|knn}/{z}/{x}/{y}.png
(local, gitignored). data/desacuerdo.json IS versioned — same pattern as
data/metrics.json: regenerated by this script, never hand-edited.
"""

import argparse
import datetime
import json
from pathlib import Path

import rasterio

from mapa_cultivos import desacuerdo, tiles
from mapa_cultivos.settings import DATA_DIR, REPO_ROOT, settings
from mapa_cultivos.zonas import ZONAS

# Placeholder disagreement color; Task 3 may swap it after visual validation
# against the class palette. Keep it a single constant so that change is one line.
COLOR_DESACUERDO = "#E91E8C"

CLASIFICADORES = ("rf", "knn")


def _paleta_desacuerdo() -> tuple[list[int], dict[int, int]]:
    """256-entry PIL palette with a single painted index: the disagreement color."""
    r, g, b = (int(COLOR_DESACUERDO[j : j + 2], 16) for j in (1, 3, 5))
    colores = [0] * 768
    colores[0:3] = [r, g, b]
    return colores, {1: 0}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--exports-dir", required=True, help="directorio con los GeoTIFF clasificados exportados de EE")
    parser.add_argument("--corrida", required=True, help="identificador de la corrida, ej. 2026-08-09a")
    parser.add_argument("--campania", default=settings.mnc_campania)
    args = parser.parse_args()

    exports_dir = Path(args.exports_dir)
    campania = args.campania
    destino_tiles = REPO_ROOT / "tiles"
    colores, indice = _paleta_desacuerdo()

    resultados: dict[str, dict[str, float]] = {}

    for zona in ZONAS:
        resultados[zona] = {}
        for clf in CLASIFICADORES:
            ruta_a = exports_dir / f"{zona}_{campania}_clasicas-{clf}.tif"
            ruta_b = exports_dir / f"{zona}_{campania}_embeddings-{clf}.tif"
            for ruta in (ruta_a, ruta_b):
                if not ruta.exists():
                    raise SystemExit(f"Falta el GeoTIFF esperado: {ruta}")

            with rasterio.open(ruta_a) as src_a, rasterio.open(ruta_b) as src_b:
                if src_a.shape != src_b.shape:
                    raise SystemExit(
                        f"Shapes distintos para {zona}/{clf}: "
                        f"{ruta_a.name} tiene {src_a.shape}, {ruta_b.name} tiene {src_b.shape}"
                    )
                datos_a = src_a.read(1)
                datos_b = src_b.read(1)
                transform = src_a.transform
                crs = src_a.crs

            cruce = desacuerdo.cruzar(datos_a, datos_b)
            pct = desacuerdo.porcentaje(cruce)
            resultados[zona][clf] = round(pct, 4)

            # Only disagreement pixels get painted: agreement (0) becomes nodata.
            cruce[cruce == 0] = 255
            n = tiles.tilear(
                cruce, transform, crs, destino_tiles,
                partes=(args.corrida, zona, campania, f"desacuerdo-{clf}"),
                colores=colores, indice=indice,
            )
            print(f"{zona} {clf}: {pct * 100:.1f} % de desacuerdo, {n} tiles")

    payload = {
        "generado": datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "corrida": args.corrida,
        "zonas": resultados,
    }
    ruta_json = DATA_DIR / "desacuerdo.json"
    ruta_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    print(f"Escrito {ruta_json}")


if __name__ == "__main__":
    main()
